version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
